In [1]:
import numpy as np

## Datatypes and Attributes

In [3]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
zeros = np.zeros((4,4))

In [5]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ndim(zeros)

2

In [8]:
np.dtype

numpy.dtype

In [9]:
ones.dtype

dtype('float64')

In [12]:
range_arrays = np.arange(0, 10)
range_arrays

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
random_int = np.random.randint(0, 10, size=(4,4))

In [14]:
random_int

array([[1, 3, 5, 3],
       [1, 6, 1, 3],
       [5, 0, 0, 7],
       [6, 9, 5, 7]])

In [15]:
np.random.random(4)

array([0.63899771, 0.26868568, 0.82663304, 0.35405104])

In [20]:
arr_4x4 = np.random.randint(10, 20, size=(4,4,4,4))

In [21]:
arr_4x4

array([[[[16, 10, 11, 16],
         [14, 17, 14, 12],
         [17, 16, 19, 11],
         [15, 13, 10, 16]],

        [[17, 18, 11, 16],
         [15, 10, 19, 10],
         [17, 11, 17, 14],
         [18, 11, 15, 15]],

        [[14, 10, 11, 16],
         [13, 14, 17, 11],
         [16, 17, 12, 19],
         [13, 10, 18, 14]],

        [[17, 13, 12, 12],
         [13, 16, 10, 15],
         [11, 12, 18, 14],
         [13, 16, 12, 11]]],


       [[[17, 14, 18, 16],
         [17, 15, 12, 12],
         [11, 15, 10, 16],
         [17, 13, 19, 13]],

        [[13, 18, 11, 16],
         [11, 10, 19, 15],
         [14, 13, 18, 14],
         [10, 11, 19, 17]],

        [[10, 19, 18, 13],
         [16, 10, 18, 14],
         [16, 19, 15, 12],
         [16, 19, 11, 11]],

        [[12, 12, 10, 15],
         [12, 11, 15, 19],
         [13, 15, 12, 13],
         [13, 12, 10, 16]]],


       [[[16, 14, 15, 16],
         [14, 12, 19, 17],
         [19, 11, 10, 13],
         [11, 13, 12, 11]],

      