In [1]:
import numpy as np

## Datatypes and Attributes

In [3]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
zeros = np.zeros((4,4))

In [5]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ndim(zeros)

2

In [8]:
np.dtype

numpy.dtype

In [9]:
ones.dtype

dtype('float64')

In [12]:
range_arrays = np.arange(0, 10)
range_arrays

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
random_int = np.random.randint(0, 10, size=(4,4))

In [14]:
random_int

array([[1, 3, 5, 3],
       [1, 6, 1, 3],
       [5, 0, 0, 7],
       [6, 9, 5, 7]])